[phases.setup]
nixPkgs = ["ffmpeg", "nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["echo done"]

[start]
cmd = "node -e \"require('ts-node').register({transpileOnly:true}); require('./index.ts')\""
